<!doctype html>
<html lang="<?=page::lang()?>">
    <head>
        <title><?=page::title()?></title>
        <?php
        
            page::style( 'http://static.devmonks.net/css/reset.min.css' );
            page::style( '/css/devmonks.base.css' );
            page::style( '/css/devmonks.grid-1080.css' );
            page::style( '/css/screen.css' );
            page::style( '/css/jquery-ui.css' );
            page::script( '/js/jquery-1.8.3.min.js' );
            page::script( '/js/jquery-ui-1.9.2.custom.min.js' );
            page::script( '/js/devmonks.jquery.js' );
            page::script( '/js/devmonks.jquery-ui.js' );
            page::script( '/js/lok.jquery-ui.js' );
            
        ?>
        <?=page::styles()?>
        <?=page::scripts()?>
    </head>
    <body>

        <div id="main" class="grid">
            
            <header class="grid-1-1-margin-10-y">
                Header
            </header>
            
            <div id="sidebar" class="grid-1-4">
                <?=page::section( 'left' )?>
            </div>
            <div id="content" class="grid-1-2-margin-10-left">
                <?=page::content()?>
            </div>
            <div id="sidebar" class="grid-1-4">
                <?=page::section( 'right' )?>
            </div>
            
            <footer class="grid-1-1-margin-10-y">
                Footer
            </footer>
        </div>
        
        
        <?=page::section( 'body' )?>
        
    </body>
</html>